import fs from "fs";

// eslint-disable-next-line no-restricted-imports
import packageJson from "../package.json";

export async function generateMeta(ids: Record<string, Record<string, string[]>>) {
    const meta = {
        version: packageJson.version,
        ids,
    };

    const metaStr = `/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT IT MANUALLY. */
    
export const tachyonMeta = ${JSON.stringify(meta, null, 4)} as const;`;

    await fs.promises.writeFile("src/meta.ts", metaStr);
}
