/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT IT MANUALLY. */
    
export const tachyonMeta = {
    "version": "0.3.1",
    "ids": {
        "bot": {
            "slave": [
                "request",
                "response"
            ],
            "unslave": [
                "request",
                "response"
            ]
        },
        "customBattle": {
            "close": [
                "request",
                "response"
            ],
            "create": [
                "request",
                "response"
            ],
            "join": [
                "request",
                "response"
            ],
            "joined": [
                "response"
            ],
            "leave": [
                "request",
                "response"
            ],
            "left": [
                "response"
            ],
            "list": [
                "request",
                "response"
            ],
            "receiveMessage": [
                "response"
            ],
            "sendMessage": [
                "request",
                "response"
            ],
            "subscribe": [
                "request",
                "response"
            ],
            "unsubscribe": [
                "request",
                "response"
            ],
            "updated": [
                "response"
            ]
        },
        "game": {
            "launch": [
                "response"
            ]
        },
        "matchmaking": {
            "cancel": [
                "request",
                "response"
            ],
            "found": [
                "response"
            ],
            "list": [
                "request",
                "response"
            ],
            "lost": [
                "response"
            ],
            "queue": [
                "request",
                "response"
            ],
            "queueUpdate": [
                "response"
            ],
            "ready": [
                "request",
                "response"
            ],
            "readyUpdate": [
                "response"
            ]
        },
        "system": {
            "connected": [
                "response"
            ],
            "disconnect": [
                "request",
                "response"
            ],
            "serverStats": [
                "request",
                "response"
            ]
        }
    }
} as const;